"function"!=typeof DIL&&(DIL=function(a,c){var d=[],e,l;a!==Object(a)&&(a={});var k,m,r,u,y,z,s,D,A,I,B;k=a.partner;m=a.containerNSID;r=a.iframeAttachmentDelay;u=!!a.disableDestinationPublishingIframe;y=a.iframeAkamaiHTTPS;z=a.mappings;s=a.uuidCookie;D=!0===a.enableErrorReporting;A=a.visitorService;I=a.declaredId;B=!0===a.removeFinishedScriptsAndCallbacks;var J,K,E;J=!0===a.disableScriptAttachment;K=!0===a.disableDefaultRequest;E=a.afterResultForDefaultRequest;D&&DIL.errorModule.activate();var L=
!0===window._dil_unit_tests;(e=c)&&d.push(e+"");if(!k||"string"!=typeof k)return e="DIL partner is invalid or not specified in initConfig",DIL.errorModule.handleError({name:"error",message:e,filename:"dil.js"}),Error(e);e="DIL containerNSID is invalid or not specified in initConfig, setting to default of 0";if(m||"number"==typeof m)m=parseInt(m,10),!isNaN(m)&&0<=m&&(e="");e&&(m=0,d.push(e),e="");l=DIL.getDil(k,m);if(l instanceof DIL&&l.api.getPartner()==k&&l.api.getContainerNSID()==m)return l;if(this instanceof
DIL)DIL.registerDil(this,k,m);else return new DIL(a,"DIL was not instantiated with the 'new' operator, returning a valid instance with partner \x3d "+k+" and containerNSID \x3d "+m);var v={IS_HTTPS:"https:"==document.location.protocol,POST_MESSAGE_ENABLED:!!window.postMessage,COOKIE_MAX_EXPIRATION_DATE:"Tue, 19 Jan 2038 03:14:07 UTC"},F={stuffed:{}},p={},n={firingQueue:[],fired:[],firing:!1,sent:[],errored:[],reservedKeys:{sids:!0,pdata:!0,logdata:!0,callback:!0,postCallbackFn:!0,useImageRequest:!0},
callbackPrefix:"demdexRequestCallback",firstRequestHasFired:!1,useJSONP:!0,abortRequests:!1,num_of_jsonp_responses:0,num_of_jsonp_errors:0,num_of_img_responses:0,num_of_img_errors:0,toRemove:[],removed:[],readyToRemove:!1,adms:{TIME_TO_CATCH_ALL_REQUESTS_RELEASE:2E3,calledBack:!1,uuid:null,noVisitorAPI:!1,instance:null,releaseType:"no VisitorAPI",admsProcessingStarted:!1,process:function(b){try{if(!this.admsProcessingStarted){var f=this,h,g,a,G,e;if("function"==typeof b&&"function"==typeof b.getInstance){if(A===
Object(A)&&(h=A.namespace)&&"string"==typeof h)g=b.getInstance(h);else{this.releaseType="no namespace";this.releaseRequests();return}if(g===Object(g)&&"function"==typeof g.isAllowed&&"function"==typeof g.getGlobalVisitorID){if(!g.isAllowed()){this.releaseType="VisitorAPI not allowed";this.releaseRequests();return}this.instance=g;this.admsProcessingStarted=!0;a=function(b){"VisitorAPI"!=f.releaseType&&(f.uuid=b,f.releaseType="VisitorAPI",f.releaseRequests())};if(L&&(G=A.server)&&"string"==typeof G)g.server=
G;e=g.getGlobalVisitorID(a);if("string"==typeof e&&e.length){a(e);return}setTimeout(function(){"VisitorAPI"!=f.releaseType&&(f.releaseType="timeout",f.releaseRequests())},this.TIME_TO_CATCH_ALL_REQUESTS_RELEASE);return}this.releaseType="invalid instance"}else this.noVisitorAPI=!0;this.releaseRequests()}}catch(c){this.releaseRequests()}},releaseRequests:function(){this.calledBack=!0;n.registerRequest()},getGlobalVisitorID:function(){return this.instance?this.instance.getGlobalVisitorID():null}},declaredId:{uuid:null,
declaredId:{init:null,request:null},declaredIdCombos:{},dIdAlwaysOn:!1,dIdInRequest:!1,setDeclaredId:function(b,f){var h=t.isPopulatedString,g=encodeURIComponent;if(b===Object(b)&&h(f)){var a=b.dpid,e=b.dpuuid,c=null;if(h(a)&&h(e)){c=g(a)+"$"+g(e);if(!0===this.declaredIdCombos[c])return"setDeclaredId: combo exists for type '"+f+"'";this.declaredIdCombos[c]=!0;this.declaredId[f]={dpid:a,dpuuid:e};"init"==f?this.dIdAlwaysOn=!0:"request"==f&&(this.dIdInRequest=!0);return"setDeclaredId: succeeded for type '"+
f+"'"}}return"setDeclaredId: failed for type '"+f+"'"},getDeclaredIdQueryString:function(){var b=this.declaredId.request,f=this.declaredId.init,h="";null!==b?h="\x26d_dpid\x3d"+b.dpid+"\x26d_dpuuid\x3d"+b.dpuuid:null!==f&&(h="\x26d_dpid\x3d"+f.dpid+"\x26d_dpuuid\x3d"+f.dpuuid);return h},getUUIDQueryString:function(){var b=n.adms,f=t.isPopulatedString,h=!1,g=n.adms.getGlobalVisitorID();f(this.uuid)?f(g)&&this.uuid!=g&&(this.uuid=g):this.uuid=g||b.uuid;if(this.dIdAlwaysOn||this.dIdInRequest)h=!0,this.dIdInRequest=
!1;return f(this.uuid)&&h?"d_uuid\x3d"+this.uuid+"\x26":""}},registerRequest:function(b){var f=this.firingQueue;b===Object(b)&&f.push(b);!this.firing&&f.length&&(this.adms.calledBack?(b=f.shift(),b.src=b.src.replace(/demdex.net\/event\?d_nsid=/,"demdex.net/event?"+this.declaredId.getUUIDQueryString()+"d_nsid\x3d"),w.fireRequest(b),!this.firstRequestHasFired&&"script"==b.tag&&(this.firstRequestHasFired=!0)):this.processVisitorAPI())},processVisitorAPI:function(){this.adms.process(window.Visitor)},
requestRemoval:function(b){if(!B)return"removeFinishedScriptsAndCallbacks is not boolean true";var f=this.toRemove,h,g;b===Object(b)&&(h=b.script,g=b.callbackName,(h===Object(h)&&"SCRIPT"==h.nodeName||"no script created"==h)&&("string"==typeof g&&g.length)&&f.push(b));if(this.readyToRemove&&f.length){g=f.shift();h=g.script;g=g.callbackName;"no script created"!=h?(b=h.src,h.parentNode.removeChild(h)):b=h;window[g]=null;try{delete window[g]}catch(a){}this.removed.push({scriptSrc:b,callbackName:g});
DIL.variables.scriptsRemoved.push(b);DIL.variables.callbacksRemoved.push(g);return this.requestRemoval()}return"requestRemoval() processed"}};l=function(){var b="http://fast.";v.IS_HTTPS&&(b=!0===y?"https://fast.":"https://");return b+k+".demdex.net/dest4.html?d_nsid\x3d"+m+"#"+encodeURIComponent(document.location.href)};var x={THROTTLE_START:3E4,throttleTimerSet:!1,id:"destination_publishing_iframe_"+k+"_"+m,url:l(),iframe:null,iframeHasLoaded:!1,sendingMessages:!1,messages:[],messagesPosted:[],
messageSendingInterval:v.POST_MESSAGE_ENABLED?15:100,jsonProcessed:[],attachIframe:function(){var b=this,f=document.createElement("iframe");f.id=this.id;f.style.cssText="display: none; width: 0; height: 0;";f.src=this.url;q.addListener(f,"load",function(){b.iframeHasLoaded=!0;b.requestToProcess()});document.body.appendChild(f);this.iframe=f},requestToProcess:function(b,f){var h=this;b&&!t.isEmptyObject(b)&&this.process(b,f);this.iframeHasLoaded&&(this.messages.length&&!this.sendingMessages)&&(this.throttleTimerSet||
(this.throttleTimerSet=!0,setTimeout(function(){h.messageSendingInterval=v.POST_MESSAGE_ENABLED?15:150},this.THROTTLE_START)),this.sendingMessages=!0,this.sendMessages())},process:function(b,f){var h=encodeURIComponent,g,a,e,c,d,k;f===Object(f)&&(k=q.encodeAndBuildRequest([n.declaredId.uuid||"",f.dpid||"",f.dpuuid||""],","));if((g=b.dests)&&g instanceof Array&&(a=g.length))for(e=0;e<a;e++)c=g[e],c=[h("dests"),h(c.id||""),h(c.y||""),h(c.c||"")],this.addMessage(c.join("|"));if((g=b.ibs)&&g instanceof
Array&&(a=g.length))for(e=0;e<a;e++)c=g[e],c=[h("ibs"),h(c.id||""),h(c.tag||""),q.encodeAndBuildRequest(c.url||[],","),h(c.ttl||""),"",k],this.addMessage(c.join("|"));if((g=b.dpcalls)&&g instanceof Array&&(a=g.length))for(e=0;e<a;e++)c=g[e],d=c.callback||{},d=[d.obj||"",d.fn||"",d.key||"",d.tag||"",d.url||""],c=[h("dpm"),h(c.id||""),h(c.tag||""),q.encodeAndBuildRequest(c.url||[],","),h(c.ttl||""),q.encodeAndBuildRequest(d,","),k],this.addMessage(c.join("|"));this.jsonProcessed.push(b)},addMessage:function(b){var f=
encodeURIComponent,f=D?f("---destpub-debug---"):f("---destpub---");this.messages.push(f+b)},sendMessages:function(){var b=this,f;this.messages.length?(f=this.messages.shift(),DIL.xd.postMessage(f,this.url,this.iframe.contentWindow),this.messagesPosted.push(f),setTimeout(function(){b.sendMessages()},this.messageSendingInterval)):this.sendingMessages=!1}},H={traits:function(b){t.isValidPdata(b)&&(p.sids instanceof Array||(p.sids=[]),q.extendArray(p.sids,b));return this},pixels:function(b){t.isValidPdata(b)&&
(p.pdata instanceof Array||(p.pdata=[]),q.extendArray(p.pdata,b));return this},logs:function(b){t.isValidLogdata(b)&&(p.logdata!==Object(p.logdata)&&(p.logdata={}),q.extendObject(p.logdata,b));return this},customQueryParams:function(b){t.isEmptyObject(b)||q.extendObject(p,b,n.reservedKeys);return this},signals:function(b,f){var h,g=b;if(!t.isEmptyObject(g)){if(f&&"string"==typeof f)for(h in g={},b)b.hasOwnProperty(h)&&(g[f+h]=b[h]);q.extendObject(p,g,n.reservedKeys)}return this},declaredId:function(b){n.declaredId.setDeclaredId(b,
"request");return this},result:function(b){"function"==typeof b&&(p.callback=b);return this},afterResult:function(b){"function"==typeof b&&(p.postCallbackFn=b);return this},useImageRequest:function(){p.useImageRequest=!0;return this},clearData:function(){p={};return this},submit:function(){w.submitRequest(p);p={};return this},getPartner:function(){return k},getContainerNSID:function(){return m},getEventLog:function(){return d},getState:function(){var b={},f={};q.extendObject(b,n,{callbackPrefix:!0,
useJSONP:!0,registerRequest:!0});q.extendObject(f,x,{attachIframe:!0,requestToProcess:!0,process:!0,sendMessages:!0});return{pendingRequest:p,otherRequestInfo:b,destinationPublishingInfo:f}},idSync:function(b){if(b!==Object(b)||"string"!=typeof b.dpid||!b.dpid.length)return"Error: config or config.dpid is empty";if("string"!=typeof b.url||!b.url.length)return"Error: config.url is empty";var f=b.url,h=b.minutesToLive,g=encodeURIComponent,a=n.declaredId,f=f.replace(/^https:/,"").replace(/^http:/,"");
if("undefined"==typeof h)h=20160;else if(h=parseInt(h,10),isNaN(h)||0>=h)return"Error: config.minutesToLive needs to be a positive number";a=q.encodeAndBuildRequest([n.adms.getGlobalVisitorID()||a.uuid||"",b.dpid,b.dpuuid||""],",");b=["ibs",g(b.dpid),"img",g(f),h,"",a];x.addMessage(b.join("|"));n.firstRequestHasFired&&x.requestToProcess();return"Successfully queued"},aamIdSync:function(b){if(b!==Object(b)||"string"!=typeof b.dpuuid||!b.dpuuid.length)return"Error: config or config.dpuuid is empty";
b.url="//dpm.demdex.net/ibs:dpid\x3d"+b.dpid+"\x26dpuuid\x3d"+b.dpuuid;return this.idSync(b)},passData:function(b){if(t.isEmptyObject(b))return"Error: json is empty or not an object";w.defaultCallback(b);return"json submitted for processing"}},w={submitRequest:function(b){n.registerRequest(w.createQueuedRequest(b));return!0},createQueuedRequest:function(b){var f=n,h,g=b.callback,a="img";if(!t.isEmptyObject(z)){var c,e,d;for(c in z)if(z.hasOwnProperty(c)&&(e=z[c],!(null==e||""===e)&&c in b&&!(e in
b)&&!(e in n.reservedKeys)))d=b[c],null==d||""===d||(b[e]=d)}t.isValidPdata(b.sids)||(b.sids=[]);t.isValidPdata(b.pdata)||(b.pdata=[]);t.isValidLogdata(b.logdata)||(b.logdata={});b.logdataArray=q.convertObjectToKeyValuePairs(b.logdata,"\x3d",!0);b.logdataArray.push("_ts\x3d"+(new Date).getTime());"function"!=typeof g&&(g=this.defaultCallback);if(f.useJSONP=!b.useImageRequest||"boolean"!=typeof b.useImageRequest)a="script",h=f.callbackPrefix+"_"+k+"_"+m+"_"+(new Date).getTime();return{tag:a,src:w.makeRequestSrc(b,
h),internalCallbackName:h,callbackFn:g,postCallbackFn:b.postCallbackFn,useImageRequest:b.useImageRequest,requestData:b}},defaultCallback:function(b,f){var h,g,a,c,e,d,k,l,m;if((h=b.stuff)&&h instanceof Array&&(g=h.length))for(a=0;a<g;a++)if((c=h[a])&&c===Object(c)){e=c.cn;d=c.cv;k=c.ttl;if("undefined"==typeof k||""===k)k=Math.floor(q.getMaxCookieExpiresInMinutes()/60/24);l=c.dmn||"."+document.domain.replace(/^www\./,"");m=c.type;if(e&&(d||"number"==typeof d))"var"!=m&&(k=parseInt(k,10))&&!isNaN(k)&&
q.setCookie(e,d,1440*k,"/",l,!1),F.stuffed[e]=d}h=b.uuid;g=n.declaredId;a=t.isPopulatedString;if(a(h)&&(a(g.uuid)||(g.uuid=h),!t.isEmptyObject(s))){g=s.path;if("string"!=typeof g||!g.length)g="/";a=parseInt(s.days,10);isNaN(a)&&(a=100);q.setCookie(s.name||"aam_did",h,1440*a,g,s.domain||"."+document.domain.replace(/^www\./,""),!0===s.secure)}!u&&!n.abortRequests&&x.requestToProcess(b,f)},makeRequestSrc:function(b,f){b.sids=t.removeEmptyArrayValues(b.sids||[]);b.pdata=t.removeEmptyArrayValues(b.pdata||
[]);var h=n,a=q.encodeAndBuildRequest(b.sids,","),c=q.encodeAndBuildRequest(b.pdata,","),e=(b.logdataArray||[]).join("\x26");delete b.logdataArray;var d=v.IS_HTTPS?"https://":"http://",l=h.declaredId.getDeclaredIdQueryString(),s;s=[];var r,u,p,y;for(r in b)if(!(r in h.reservedKeys)&&b.hasOwnProperty(r))if(u=b[r],r=encodeURIComponent(r),u instanceof Array){p=0;for(y=u.length;p<y;p++)s.push(r+"\x3d"+encodeURIComponent(u[p]))}else s.push(r+"\x3d"+encodeURIComponent(u));s=s.length?"\x26"+s.join("\x26"):
"";return d+k+".demdex.net/event?d_nsid\x3d"+m+l+(a.length?"\x26d_sid\x3d"+a:"")+(c.length?"\x26d_px\x3d"+c:"")+(e.length?"\x26d_ld\x3d"+encodeURIComponent(e):"")+s+(h.useJSONP?"\x26d_rtbd\x3djson\x26d_jsonv\x3d"+DIL.jsonVersion+"\x26d_dst\x3d1\x26d_cts\x3d1\x26d_cb\x3d"+(f||""):"")},fireRequest:function(b){if("img"==b.tag)this.fireImage(b);else if("script"==b.tag){var f=n.declaredId,f=f.declaredId.request||f.declaredId.init||{};this.fireScript(b,{dpid:f.dpid||"",dpuuid:f.dpuuid||""})}},fireImage:function(b){var f=
n,a,g;f.abortRequests||(f.firing=!0,a=new Image(0,0),f.sent.push(b),a.onload=function(){f.firing=!1;f.fired.push(b);f.num_of_img_responses++;f.registerRequest()},g=function(a){e="imgAbortOrErrorHandler received the event of type "+a.type;d.push(e);f.abortRequests=!0;f.firing=!1;f.errored.push(b);f.num_of_img_errors++;f.registerRequest()},a.addEventListener?(a.addEventListener("error",g,!1),a.addEventListener("abort",g,!1)):a.attachEvent&&(a.attachEvent("onerror",g),a.attachEvent("onabort",g)),a.src=
b.src)},fireScript:function(b,f){var a=this,g=n,c,l,m=b.src,s=b.postCallbackFn,r="function"==typeof s,u=b.internalCallbackName;g.abortRequests||(g.firing=!0,window[u]=function(a){try{a!==Object(a)&&(a={});var h=b.callbackFn;g.firing=!1;g.fired.push(b);g.num_of_jsonp_responses++;h(a,f);r&&s(a,f)}catch(c){c.message="DIL jsonp callback caught error with message "+c.message;e=c.message;d.push(e);c.filename=c.filename||"dil.js";c.partner=k;DIL.errorModule.handleError(c);try{h({error:c.name+"|"+c.message}),
r&&s({error:c.name+"|"+c.message})}catch(m){}}finally{g.requestRemoval({script:l,callbackName:u}),g.registerRequest()}},J?(g.firing=!1,g.requestRemoval({script:"no script created",callbackName:u})):(l=document.createElement("script"),l.addEventListener&&l.addEventListener("error",function(f){g.requestRemoval({script:l,callbackName:u});e="jsonp script tag error listener received the event of type "+f.type+" with src "+m;a.handleScriptError(e,b)},!1),l.type="text/javascript",l.src=m,c=DIL.variables.scriptNodeList[0],
c.parentNode.insertBefore(l,c)),g.sent.push(b),g.declaredId.declaredId.request=null)},handleScriptError:function(b,f){var a=n;d.push(b);a.abortRequests=!0;a.firing=!1;a.errored.push(f);a.num_of_jsonp_errors++;a.registerRequest()}},t={isValidPdata:function(b){return b instanceof Array&&this.removeEmptyArrayValues(b).length?!0:!1},isValidLogdata:function(b){return!this.isEmptyObject(b)},isEmptyObject:function(b){if(b!==Object(b))return!0;for(var a in b)if(b.hasOwnProperty(a))return!1;return!0},removeEmptyArrayValues:function(b){for(var a=
0,c=b.length,g,e=[],a=0;a<c;a++)g=b[a],"undefined"!=typeof g&&null!=g&&e.push(g);return e},isPopulatedString:function(b){return"string"==typeof b&&b.length}},q={addListener:function(){if(document.addEventListener)return function(b,a,c){b.addEventListener(a,function(b){"function"==typeof c&&c(b)},!1)};if(document.attachEvent)return function(b,a,c){b.attachEvent("on"+a,function(b){"function"==typeof c&&c(b)})}}(),convertObjectToKeyValuePairs:function(b,a,c){var g=[];a=a||"\x3d";var e,d;for(e in b)d=
b[e],"undefined"!=typeof d&&null!=d&&g.push(e+a+(c?encodeURIComponent(d):d));return g},encodeAndBuildRequest:function(b,a){return this.map(b,function(b){return encodeURIComponent(b)}).join(a)},map:function(b,a){if(Array.prototype.map)return b.map(a);if(void 0===b||null===b)throw new TypeError;var c=Object(b),g=c.length>>>0;if("function"!==typeof a)throw new TypeError;for(var e=Array(g),d=0;d<g;d++)d in c&&(e[d]=a.call(a,c[d],d,c));return e},filter:function(b,a){if(!Array.prototype.filter){if(void 0===
b||null===b)throw new TypeError;var c=Object(b),e=c.length>>>0;if("function"!==typeof a)throw new TypeError;for(var d=[],k=0;k<e;k++)if(k in c){var l=c[k];a.call(a,l,k,c)&&d.push(l)}return d}return b.filter(a)},getCookie:function(b){b+="\x3d";var a=document.cookie.split(";"),c,e,d;c=0;for(e=a.length;c<e;c++){for(d=a[c];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(b))return decodeURIComponent(d.substring(b.length,d.length))}return null},setCookie:function(b,a,c,e,d,k){var l=new Date;
c&&(c*=6E4);document.cookie=b+"\x3d"+encodeURIComponent(a)+(c?";expires\x3d"+(new Date(l.getTime()+c)).toUTCString():"")+(e?";path\x3d"+e:"")+(d?";domain\x3d"+d:"")+(k?";secure":"")},extendArray:function(b,a){return b instanceof Array&&a instanceof Array?(Array.prototype.push.apply(b,a),!0):!1},extendObject:function(b,a,c){var e;if(b===Object(b)&&a===Object(a)){for(e in a)if(a.hasOwnProperty(e)&&(t.isEmptyObject(c)||!(e in c)))b[e]=a[e];return!0}return!1},getMaxCookieExpiresInMinutes:function(){return((new Date(v.COOKIE_MAX_EXPIRATION_DATE)).getTime()-
(new Date).getTime())/1E3/60}};"error"==k&&0==m&&q.addListener(window,"load",function(){DIL.windowLoaded=!0});var C=function(){N();!u&&!n.abortRequests&&x.attachIframe();n.readyToRemove=!0;n.requestRemoval()},N=function(){u||setTimeout(function(){!K&&(!n.firstRequestHasFired&&!n.adms.admsProcessingStarted&&!n.adms.calledBack)&&("function"==typeof E?H.afterResult(E).submit():H.submit())},DIL.constants.TIME_TO_DEFAULT_REQUEST)},M=document;"error"!=k&&(DIL.windowLoaded?C():"complete"!=M.readyState&&
"loaded"!=M.readyState?q.addListener(window,"load",C):DIL.isAddedPostWindowLoadWasCalled?q.addListener(window,"load",C):(r="number"==typeof r?parseInt(r,10):0,0>r&&(r=0),setTimeout(C,r||DIL.constants.TIME_TO_CATCH_ALL_DP_IFRAME_ATTACHMENT)));n.declaredId.setDeclaredId(I,"init");this.api=H;this.getStuffedVariable=function(b){var a=F.stuffed[b];!a&&"number"!=typeof a&&(a=q.getCookie(b),!a&&"number"!=typeof a&&(a=""));return a};this.validators=t;this.helpers=q;this.constants=v;this.log=d;L&&(this.pendingRequest=
p,this.requestController=n,this.setDestinationPublishingUrl=l,this.destinationPublishing=x,this.requestProcs=w,this.variables=F)},function(){var a=document,c;null==a.readyState&&a.addEventListener&&(a.readyState="loading",a.addEventListener("DOMContentLoaded",c=function(){a.removeEventListener("DOMContentLoaded",c,!1);a.readyState="complete"},!1))}(),DIL.extendStaticPropertiesAndMethods=function(a){var c;if(a===Object(a))for(c in a)a.hasOwnProperty(c)&&(this[c]=a[c])},DIL.extendStaticPropertiesAndMethods({version:"4.6",
jsonVersion:1,constants:{TIME_TO_DEFAULT_REQUEST:50,TIME_TO_CATCH_ALL_DP_IFRAME_ATTACHMENT:500},variables:{scriptNodeList:document.getElementsByTagName("script"),scriptsRemoved:[],callbacksRemoved:[]},windowLoaded:!1,dils:{},isAddedPostWindowLoadWasCalled:!1,isAddedPostWindowLoad:function(a){this.isAddedPostWindowLoadWasCalled=!0;this.windowLoaded="function"==typeof a?!!a():"boolean"==typeof a?a:!0},create:function(a){try{return new DIL(a)}catch(c){return(new Image(0,0)).src="http://error.demdex.net/event?d_nsid\x3d0\x26d_px\x3d14137\x26d_ld\x3dname%3Derror%26filename%3Ddil.js%26partner%3Dno_partner%26message%3DError%2520in%2520attempt%2520to%2520create%2520DIL%2520instance%2520with%2520DIL.create()%26_ts%3D"+
(new Date).getTime(),Error("Error in attempt to create DIL instance with DIL.create()")}},registerDil:function(a,c,d){c=c+"$"+d;c in this.dils||(this.dils[c]=a)},getDil:function(a,c){var d;"string"!=typeof a&&(a="");c||(c=0);d=a+"$"+c;return d in this.dils?this.dils[d]:Error("The DIL instance with partner \x3d "+a+" and containerNSID \x3d "+c+" was not found")},dexGetQSVars:function(a,c,d){c=this.getDil(c,d);return c instanceof this?c.getStuffedVariable(a):""},xd:{postMessage:function(a,c,d){var e=
1;c&&(window.postMessage?d.postMessage(a,c.replace(/([^:]+:\/\/[^\/]+).*/,"$1")):c&&(d.location=c.replace(/#.*$/,"")+"#"+ +new Date+e++ +"\x26"+a))}}}),DIL.errorModule=function(){var a=DIL.create({partner:"error",containerNSID:0,disableDestinationPublishingIframe:!0}),c={harvestererror:14138,destpuberror:14139,dpmerror:14140,generalerror:14137,error:14137,noerrortypedefined:15021,evalerror:15016,rangeerror:15017,referenceerror:15018,typeerror:15019,urierror:15020},d=!1;return{activate:function(){d=
!0},handleError:function(e){if(!d)return"DIL error module has not been activated";e!==Object(e)&&(e={});var l=e.name?(new String(e.name)).toLowerCase():"",k=[];e={name:l,filename:e.filename?e.filename+"":"",partner:e.partner?e.partner+"":"no_partner",site:e.site?e.site+"":document.location.href,message:e.message?e.message+"":""};k.push(l in c?c[l]:c.noerrortypedefined);a.api.pixels(k).logs(e).useImageRequest().submit();return"DIL error report sent"},pixelMap:c}}(),DIL.tools={},DIL.modules={helpers:{handleModuleError:function(a,
c,d){var e="";c=c||"Error caught in DIL module/submodule: ";a===Object(a)?e=c+(a.message||"err has no message"):(e=c+"err is not a valid object",a={});a.message=e;d instanceof DIL&&(a.partner=d.api.getPartner());DIL.errorModule.handleError(a);return this.errorMessage=e}}});
DIL.tools.getSearchReferrer=function(a,c){var d=DIL.getDil("error"),e=DIL.tools.decomposeURI(a||document.referrer),l="",k="",m={queryParam:"q"},l=d.helpers.filter([c===Object(c)?c:{},{hostPattern:/aol\./},{hostPattern:/ask\./},{hostPattern:/bing\./},{hostPattern:/google\./},{hostPattern:/yahoo\./,queryParam:"p"}],function(a){return!(!a.hasOwnProperty("hostPattern")||!e.hostname.match(a.hostPattern))}).shift();return!l?{valid:!1,name:"",keywords:""}:{valid:!0,name:e.hostname,keywords:(d.helpers.extendObject(m,
l),k=m.queryPattern?(l=(""+e.search).match(m.queryPattern))?l[1]:"":e.uriParams[m.queryParam],decodeURIComponent(k||"").replace(/\+|%20/g," "))}};
DIL.tools.decomposeURI=function(a){var c=DIL.getDil("error"),d=document.createElement("a");d.href=a||document.referrer;return{hash:d.hash,host:d.host.split(":").shift(),hostname:d.hostname,href:d.href,pathname:d.pathname.replace(/^\//,""),protocol:d.protocol,search:d.search,uriParams:function(a,d){c.helpers.map(d.split("\x26"),function(c){c=c.split("\x3d");a[c.shift()]=c.shift()});return a}({},d.search.replace(/^(\/|\?)?|\/$/g,""))}};
DIL.tools.getMetaTags=function(){var a={},c=document.getElementsByTagName("meta"),d,e,l,k,m;d=0;for(l=arguments.length;d<l;d++)if(k=arguments[d],null!==k)for(e=0;e<c.length;e++)if(m=c[e],m.name==k){a[k]=m.content;break}return a};
DIL.modules.siteCatalyst={dil:null,handle:DIL.modules.helpers.handleModuleError,init:function(a,c,d){try{var e=this,l={name:"DIL Site Catalyst Module Error"},k=function(a){l.message=a;DIL.errorModule.handleError(l);return a};this.dil=null;if(c instanceof DIL)this.dil=c;else return k("dilInstance is not a valid instance of DIL");l.partner=c.api.getPartner();if(a!==Object(a))return k("siteCatalystReportingSuite is not an object");if("function"!=typeof a.m_i||"function"!=typeof a.loadModule)return k("s.m_i is not a function or s.loadModule is not a function");
a.m_DIL=function(a){a=a.m_i("DIL");if(a!==Object(a))return k("m is not an object");a.trackVars=e.constructTrackVars(d);a.d=0;a._t=function(){var a,c,e=","+this.trackVars+",",d=this.s,l,m=[];l=[];var r={},B=!1;if(d!==Object(d)||!(d.va_t instanceof Array))return k("Error in m._t function: s is not an object or s.va_t is not an array");if(this.d){if(d.lightProfileID)(a=d.lightTrackVars)&&(a=","+a+","+d.vl_mr+",");else if(d.pe||d.linkType)a=d.linkTrackVars,d.pe&&(c=d.pe.substring(0,1).toUpperCase()+d.pe.substring(1),
d[c]&&(a=d[c].trackVars)),a&&(a=","+a+","+d.vl_l+","+d.vl_l2+",");if(a){c=0;for(m=a.split(",");c<m.length;c++)0<=e.indexOf(","+m[c]+",")&&l.push(m[c]);l.length&&(e=","+l.join(",")+",")}l=0;for(c=d.va_t.length;l<c;l++)a=d.va_t[l],0<=e.indexOf(","+a+",")&&(null!=d[a]&&""!==d[a])&&(r[a]=d[a],B=!0);B&&this.d.api.signals(r,"c_").submit()}};a.setup=function(a,d){this.d=c}};a.loadModule("DIL");if(a.DIL!==Object(a.DIL)||"function"!=typeof a.DIL.setup)return k("s.DIL is not an object or s.DIL.setup is not a function");
a.DIL.setup();if(l.message)return l.message}catch(m){return this.handle(m,"DIL.modules.siteCatalyst.init() caught error with message ",this.dil)}},constructTrackVars:function(a){var c=[],d,e,l,k,m;if(a===Object(a)){d=a.names;if(d instanceof Array&&(l=d.length))for(e=0;e<l;e++)k=d[e],"string"==typeof k&&k.length&&c.push(k);a=a.iteratedNames;if(a instanceof Array&&(l=a.length))for(e=0;e<l;e++)if(d=a[e],d===Object(d)&&(k=d.name,m=parseInt(d.maxIndex,10),"string"==typeof k&&k.length&&!isNaN(m)&&0<=m))for(d=
0;d<=m;d++)c.push(k+d);if(c.length)return c.join(",")}return this.constructTrackVars({names:"pageName channel campaign products events pe pev1 pev2 pev3".split(" "),iteratedNames:[{name:"prop",maxIndex:75},{name:"eVar",maxIndex:75}]})}};